name: Diamond_Fast_Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *' # التحديث كل دقيقة واحدة (أسرع توقيت ممكن)
jobs:
  run_fast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Quick Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip' # تسريع تثبيت المكتبات عبر التخزين المؤقت
      - name: Install
        run: pip install requests beautifulsoup4 pyTelegramBotAPI
      - name: Run
        run: python scraper.py
